server:
  port: 1801
spring: 
   profiles: dev
   application: 
    name: microservicecloud-config-dept-client
    
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
